// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeginReq.proto

#ifndef PROTOBUF_BeginReq_2eproto__INCLUDED
#define PROTOBUF_BeginReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_BeginReq_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsBeginRequestImpl();
void InitDefaultsBeginRequest();
inline void InitDefaults() {
  InitDefaultsBeginRequest();
}
}  // namespace protobuf_BeginReq_2eproto
namespace record {
class BeginRequest;
class BeginRequestDefaultTypeInternal;
extern BeginRequestDefaultTypeInternal _BeginRequest_default_instance_;
}  // namespace record
namespace record {

// ===================================================================

class BeginRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:record.BeginRequest) */ {
 public:
  BeginRequest();
  virtual ~BeginRequest();

  BeginRequest(const BeginRequest& from);

  inline BeginRequest& operator=(const BeginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BeginRequest(BeginRequest&& from) noexcept
    : BeginRequest() {
    *this = ::std::move(from);
  }

  inline BeginRequest& operator=(BeginRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BeginRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BeginRequest* internal_default_instance() {
    return reinterpret_cast<const BeginRequest*>(
               &_BeginRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BeginRequest* other);
  friend void swap(BeginRequest& a, BeginRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BeginRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  BeginRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BeginRequest& from);
  void MergeFrom(const BeginRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BeginRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string reserved1 = 3;
  bool has_reserved1() const;
  void clear_reserved1();
  static const int kReserved1FieldNumber = 3;
  const ::std::string& reserved1() const;
  void set_reserved1(const ::std::string& value);
  #if LANG_CXX11
  void set_reserved1(::std::string&& value);
  #endif
  void set_reserved1(const char* value);
  void set_reserved1(const char* value, size_t size);
  ::std::string* mutable_reserved1();
  ::std::string* release_reserved1();
  void set_allocated_reserved1(::std::string* reserved1);

  // optional int32 role = 1;
  bool has_role() const;
  void clear_role();
  static const int kRoleFieldNumber = 1;
  ::google::protobuf::int32 role() const;
  void set_role(::google::protobuf::int32 value);

  // optional int32 flags = 2;
  bool has_flags() const;
  void clear_flags();
  static const int kFlagsFieldNumber = 2;
  ::google::protobuf::int32 flags() const;
  void set_flags(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:record.BeginRequest)
 private:
  void set_has_role();
  void clear_has_role();
  void set_has_flags();
  void clear_has_flags();
  void set_has_reserved1();
  void clear_has_reserved1();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr reserved1_;
  ::google::protobuf::int32 role_;
  ::google::protobuf::int32 flags_;
  friend struct ::protobuf_BeginReq_2eproto::TableStruct;
  friend void ::protobuf_BeginReq_2eproto::InitDefaultsBeginRequestImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BeginRequest

// optional int32 role = 1;
inline bool BeginRequest::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BeginRequest::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BeginRequest::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BeginRequest::clear_role() {
  role_ = 0;
  clear_has_role();
}
inline ::google::protobuf::int32 BeginRequest::role() const {
  // @@protoc_insertion_point(field_get:record.BeginRequest.role)
  return role_;
}
inline void BeginRequest::set_role(::google::protobuf::int32 value) {
  set_has_role();
  role_ = value;
  // @@protoc_insertion_point(field_set:record.BeginRequest.role)
}

// optional int32 flags = 2;
inline bool BeginRequest::has_flags() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BeginRequest::set_has_flags() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BeginRequest::clear_has_flags() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BeginRequest::clear_flags() {
  flags_ = 0;
  clear_has_flags();
}
inline ::google::protobuf::int32 BeginRequest::flags() const {
  // @@protoc_insertion_point(field_get:record.BeginRequest.flags)
  return flags_;
}
inline void BeginRequest::set_flags(::google::protobuf::int32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:record.BeginRequest.flags)
}

// optional string reserved1 = 3;
inline bool BeginRequest::has_reserved1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BeginRequest::set_has_reserved1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BeginRequest::clear_has_reserved1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BeginRequest::clear_reserved1() {
  reserved1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reserved1();
}
inline const ::std::string& BeginRequest::reserved1() const {
  // @@protoc_insertion_point(field_get:record.BeginRequest.reserved1)
  return reserved1_.GetNoArena();
}
inline void BeginRequest::set_reserved1(const ::std::string& value) {
  set_has_reserved1();
  reserved1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:record.BeginRequest.reserved1)
}
#if LANG_CXX11
inline void BeginRequest::set_reserved1(::std::string&& value) {
  set_has_reserved1();
  reserved1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:record.BeginRequest.reserved1)
}
#endif
inline void BeginRequest::set_reserved1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_reserved1();
  reserved1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:record.BeginRequest.reserved1)
}
inline void BeginRequest::set_reserved1(const char* value, size_t size) {
  set_has_reserved1();
  reserved1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:record.BeginRequest.reserved1)
}
inline ::std::string* BeginRequest::mutable_reserved1() {
  set_has_reserved1();
  // @@protoc_insertion_point(field_mutable:record.BeginRequest.reserved1)
  return reserved1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BeginRequest::release_reserved1() {
  // @@protoc_insertion_point(field_release:record.BeginRequest.reserved1)
  clear_has_reserved1();
  return reserved1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BeginRequest::set_allocated_reserved1(::std::string* reserved1) {
  if (reserved1 != NULL) {
    set_has_reserved1();
  } else {
    clear_has_reserved1();
  }
  reserved1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reserved1);
  // @@protoc_insertion_point(field_set_allocated:record.BeginRequest.reserved1)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace record

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BeginReq_2eproto__INCLUDED
