// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stdin.proto

#ifndef PROTOBUF_stdin_2eproto__INCLUDED
#define PROTOBUF_stdin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_stdin_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStdinImpl();
void InitDefaultsStdin();
inline void InitDefaults() {
  InitDefaultsStdin();
}
}  // namespace protobuf_stdin_2eproto
namespace record {
class Stdin;
class StdinDefaultTypeInternal;
extern StdinDefaultTypeInternal _Stdin_default_instance_;
}  // namespace record
namespace record {

// ===================================================================

class Stdin : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:record.Stdin) */ {
 public:
  Stdin();
  virtual ~Stdin();

  Stdin(const Stdin& from);

  inline Stdin& operator=(const Stdin& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Stdin(Stdin&& from) noexcept
    : Stdin() {
    *this = ::std::move(from);
  }

  inline Stdin& operator=(Stdin&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stdin& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Stdin* internal_default_instance() {
    return reinterpret_cast<const Stdin*>(
               &_Stdin_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Stdin* other);
  friend void swap(Stdin& a, Stdin& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Stdin* New() const PROTOBUF_FINAL { return New(NULL); }

  Stdin* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Stdin& from);
  void MergeFrom(const Stdin& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Stdin* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string contentData = 1;
  bool has_contentdata() const;
  void clear_contentdata();
  static const int kContentDataFieldNumber = 1;
  const ::std::string& contentdata() const;
  void set_contentdata(const ::std::string& value);
  #if LANG_CXX11
  void set_contentdata(::std::string&& value);
  #endif
  void set_contentdata(const char* value);
  void set_contentdata(const char* value, size_t size);
  ::std::string* mutable_contentdata();
  ::std::string* release_contentdata();
  void set_allocated_contentdata(::std::string* contentdata);

  // optional int32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:record.Stdin)
 private:
  void set_has_contentdata();
  void clear_has_contentdata();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr contentdata_;
  ::google::protobuf::int32 type_;
  friend struct ::protobuf_stdin_2eproto::TableStruct;
  friend void ::protobuf_stdin_2eproto::InitDefaultsStdinImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Stdin

// optional string contentData = 1;
inline bool Stdin::has_contentdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stdin::set_has_contentdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stdin::clear_has_contentdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stdin::clear_contentdata() {
  contentdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_contentdata();
}
inline const ::std::string& Stdin::contentdata() const {
  // @@protoc_insertion_point(field_get:record.Stdin.contentData)
  return contentdata_.GetNoArena();
}
inline void Stdin::set_contentdata(const ::std::string& value) {
  set_has_contentdata();
  contentdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:record.Stdin.contentData)
}
#if LANG_CXX11
inline void Stdin::set_contentdata(::std::string&& value) {
  set_has_contentdata();
  contentdata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:record.Stdin.contentData)
}
#endif
inline void Stdin::set_contentdata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_contentdata();
  contentdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:record.Stdin.contentData)
}
inline void Stdin::set_contentdata(const char* value, size_t size) {
  set_has_contentdata();
  contentdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:record.Stdin.contentData)
}
inline ::std::string* Stdin::mutable_contentdata() {
  set_has_contentdata();
  // @@protoc_insertion_point(field_mutable:record.Stdin.contentData)
  return contentdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Stdin::release_contentdata() {
  // @@protoc_insertion_point(field_release:record.Stdin.contentData)
  clear_has_contentdata();
  return contentdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stdin::set_allocated_contentdata(::std::string* contentdata) {
  if (contentdata != NULL) {
    set_has_contentdata();
  } else {
    clear_has_contentdata();
  }
  contentdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), contentdata);
  // @@protoc_insertion_point(field_set_allocated:record.Stdin.contentData)
}

// optional int32 type = 2;
inline bool Stdin::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stdin::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stdin::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stdin::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Stdin::type() const {
  // @@protoc_insertion_point(field_get:record.Stdin.type)
  return type_;
}
inline void Stdin::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:record.Stdin.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace record

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stdin_2eproto__INCLUDED
